### ISSUE TITLE
Revisit sigint/sigterm while uploading files.

### ISSUE THREAD

**Issue by Robpol86** [Robpol86/FlashAirMusic#3]
Coroutine actually hangs and waits until upload is done. Stopping service may take a very long time.

**Comment by Robpol86** [comment]
```
016-02-10 18:11:48,128 4766  INFO     flash_air_music.upload.run               Uploading 4 song(s).
2016-02-10 18:11:48,129 4766  INFO     flash_air_music.upload.interface         Uploading file: /home/robpol86/fam_working_dir/ACDC - 1981 - Dirty Deeds Done Dirt Cheap - 03 - Big Balls.mp3
2016-02-10 18:11:48,130 4766  DEBUG    flash_air_music.upload.interface         Uploading to /MUSIC/_fam_staged.bin
2016-02-10 18:11:48,130 4766  DEBUG    flash_air_music.upload.api               POSTing to http://10.192.168.149/upload.cgi with file name _fam_staged.bin
2016-02-10 18:11:48,146 4766  INFO     requests.packages.urllib3.connectionpool Starting new HTTP connection (1): 10.192.168.149
^C2016-02-10 18:12:09,843 4766  DEBUG    requests.packages.urllib3.connectionpool "POST /upload.cgi HTTP/1.1" 200 303
2016-02-10 18:12:09,844 4766  DEBUG    flash_air_music.upload.api               Response code: 200
2016-02-10 18:12:09,844 4766  DEBUG    flash_air_music.upload.api               Response text: <html xmlns="http://www.w3.org/1999/xhtml"><head><META http-equiv="Content-Type" CONTENT="text/html; charset=utf-8"/><h1>Success</h1><br>
<form action=/upload.cgi method=post enctype=multipart/form-data>
<input name=file type=file size=50><br>
<input type=submit value=submit ></form>
</body></html>
2016-02-10 18:12:09,844 4766  DEBUG    flash_air_music.upload.interface         Moving to /MUSIC/ACDC - 1981 - Dirty Deeds Done Dirt Cheap - 03 - Big Balls.mp3 and setting mtime 0x484a8d69
2016-02-10 18:12:09,844 4766  DEBUG    flash_air_music.upload.api               Querying url http://10.192.168.149/MUSIC/_fam_move_touch.lua?/MUSIC/_fam_staged.bin%200x484a8d69%20/MUSIC/ACDC%20-%201981%20-%20Dirty%20Deeds%20Done%20Dirt%20Cheap%20-%2003%20-%20Big%20Balls.mp3
2016-02-10 18:12:09,845 4766  INFO     requests.packages.urllib3.connectionpool Starting new HTTP connection (1): 10.192.168.149
2016-02-10 18:12:10,368 4766  DEBUG    requests.packages.urllib3.connectionpool "GET /MUSIC/_fam_move_touch.lua?/MUSIC/_fam_staged.bin%200x484a8d69%20/MUSIC/ACDC%20-%201981%20-%20Dirty%20Deeds%20Done%20Dirt%20Cheap%20-%2003%20-%20Big%20Balls.mp3 HTTP/1.1" 400 None
2016-02-10 18:12:10,370 4766  DEBUG    flash_air_music.upload.api               Response code: 400
2016-02-10 18:12:10,411 4766  DEBUG    flash_air_music.upload.api               Response text: {"arg_source":"\/MUSIC\/_fam_staged.bin","error":"arg_mtime under 1212980759.","arg_mtime":"0x484a8d69","arg_destination":"\/MUSIC\/ACDC - 1981 - Dirty Deeds Done Dirt Cheap - 03 - Big Balls.mp3"}

2016-02-10 18:12:10,412 4766  ERROR    flash_air_music.upload.run               Unexpected exception.
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/flash_air_music/upload/run.py", line 69, in upload_cleanup
    upload_files(ip_addr, files_attrs, shutdown_future)
  File "/usr/lib/python3.4/site-packages/flash_air_music/upload/interface.py", line 220, in upload_files
    api.lua_script_execute(ip_addr, script_path, script_argv)
  File "/usr/lib/python3.4/site-packages/flash_air_music/upload/api.py", line 124, in lua_script_execute
    raise exceptions.FlashAirHTTPError(response.status_code, response)
flash_air_music.exceptions.FlashAirHTTPError: (400, <Response [400]>)
2016-02-10 18:12:10,418 4766  DEBUG    flash_air_music.upload.run               Released lock.
2016-02-10 18:12:10,418 4766  INFO     flash_air_music.upload.run               Done updating FlashAir card.
2016-02-10 18:12:10,419 4766  INFO     flash_air_music.__main__                 Caught signal 2 (SIG_SETMASK/SIGINT). Shutting down.
2016-02-10 18:12:10,420 4766  INFO     flash_air_music.__main__                 Waiting up to 5 seconds for tasks to cleanup.
2016-02-10 18:12:11,419 4766  DEBUG    flash_air_music.upload.triggers          watch_for_flashair() saw shutdown signal.
2016-02-10 18:12:11,420 4766  DEBUG    flash_air_music.convert.triggers         watch_directory() saw shutdown signal.
2016-02-10 18:12:11,426 4766  INFO     flash_air_music.__main__                 Stopping loop.
2016-02-10 18:12:11,427 4766  INFO     flash_air_music.__main__                 Main loop has exited.
```
